### ISSUE TITLE
Failed to find module: "sqlcipher"

### ISSUE THREAD

**Issue by kumarandena** [zhouchangsheng/sqlcipher#2]
I tried to integrate this module with Nativescript with angular framework's app. 

But after import, I got followed error.

Failed to find module: "sqlcipher" , relative to : app/tns_modules/
FYI, 
![screenshot_2017-08-14-15-48-54 1](https://user-images.githubusercontent.com/30895291/29268050-d9826efe-8108-11e7-9704-8de26b07e496.png)

Thanks.

**Comment by kumarandena** [comment]
# **app.component.ts**

import { Component } from "@angular/core";
var SQLite3 = require('sqlcipher').verbose();

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})

export class AppComponent {

public constructor(){
var sqlite = new SQLite3.Database('./test-win.db');
alert("test-win db created");
sqlite.run("pragma key = 'secret'");
sqlite.run("pragma cipher = 'aes-256-cbc'");

}

**Comment by zhouchangsheng** [comment]
Hi @kumaran-dena !

I don't know the environment where your project running,But I got some idea about it.On the node environment,The `node_modules` is the folder in which project dependencies files be placed, instead of `tns_modules`. However,The environment where your project running is not `node`,then  some issues would occured if you run command  like `npm install sqlcipher ...` to install sqlcipher because the module `sqlcipher` depend on `sqlite3` in folder `node_modules`,thus you have to  change `node_modules` to `tns_modules`.

## Installation
After Installing Successfully, The `sqlcipher` actually depends on `sqlite3` that has been rebuilt.So,You have to check how the `sqlite3` has associated with `sqlcipher`.

## The graph of `sqlcipher`

### 1.on windows

----sqlcipher_project
--------node_modules
------------sqlcipher
----------------node_modules
--------------------sqlite3
--------------------`others`
------------sqlite3
------------`others`

### 2.on mac
----sqlcipher_project
--------node_modules
------------sqlcipher
------------sqlite3
------------`others`

## Conclusion
So you have to check both `node_modules` and `sqlite3`,I hope that would be useful for you.
